#include "TM4C123GH6PM.h"



/* SET PE2 AS ADC
	FOR WATER SENSOR*/
void setLimit_ADC_Initialization () {
	
	
	//SYSCTL->RCGCGPIO |= 0x10; //START CLOCK FOR GPIOE
	//while( (SYSCTL->PRGPIO & 0x10) == 0x00 ) ;	/* WAIT FOR PORT E TO STABILIZE*/
	
	
	/* SET PE2 AS ADC */  /* PE2 IS AIN1 */
	GPIOE->DIR |= 0x04;
	GPIOE->AMSEL |= 0x04;
	GPIOE->AFSEL |= 0x04;
	
	SYSCTL->RCGCADC |= 0x2;  									/* START CLOCK FOR ADC1 */
	while( (SYSCTL->PRADC & 0x02) == 0x00 ) ;	/* WAIT FOR ADC1 TO STABILIZE*/


	ADC1->ACTSS &= 0x00; 			// DISABLE SAMPLER TO CONFIGURE IT  ***LAB MANUAL SAYS ONYL CONFIGURE BIT 3
	ADC1->EMUX &=  0x0FFF; 		// CONFIGURE THAT SAMPLE TRIGERRING IS BY SOFTWARE FOR SAMPLER3	
	ADC1->SSMUX3 = 0x0111 ; 		//TELL MUXSELECT3 TO TAKE INPUT FROM AIN1 
	ADC1 -> SSCTL3 |= 0x06; 	//INTERRUPT ENABLE AND FIRST SAMPLE IS LAST SAMPLE
	ADC1->PC = 0x01;					//125KSPS
	ADC1->ACTSS |= 0x08; 			// ENABLE SAMPLER3
	ADC1->PSSI |= 0x08;				// TELL SAMPLER TO START SAMPLING
	
}

uint32_t readLimits(){
	
	uint32_t value;
	ADC1->PSSI |= 0x08; //start run
	while (  (ADC1->RIS & 0x08) != 0x08  )  ; 	//INTERRUPT RAISED AND SAMPLE TAKEN 
	value = ADC1->SSFIFO3 ;	//READ MEASUREMENT
	ADC1->ISC |= 0x08;  												//CLEAR INTERRUPT
	return value;
}